FROM node:latest

WORKDIR /app

COPY package*.json ./

RUN npm install

# Google Chrome (для headless тестів)
RUN apt-get update && apt-get install -y wget gnupg2 curl \
  && wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
  && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list \
  && apt-get update && apt-get install -y google-chrome-stable --no-install-recommends \
  && rm -rf /var/lib/apt/lists/*

COPY . .

EXPOSE 4200

CMD ["npm", "run", "start"]
