server {
    listen 80;
    server_name api-dobrodiy.kn314-uz.keenetic.pro;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name api-dobrodiy.kn314-uz.keenetic.pro;

    ssl_certificate /etc/letsencrypt/live/api-dobrodiy.kn314-uz.keenetic.pro/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api-dobrodiy.kn314-uz.keenetic.pro/privkey.pem;

    location / {
        proxy_pass http://petcare_api:5100;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
