services:
  db:
    image: postgis/postgis:16-3.4
    container_name: petcare_db
    environment:
      POSTGRES_DB: petcare_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  petcare.api:
    build:
      context: .
      dockerfile: PetCare.Api/Dockerfile
    container_name: petcare_api
    depends_on:
      - db
    ports:
      - '5000:80'
    volumes:
      - "${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro"
      - "${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro"
    restart: unless-stopped

  petcare.api.sdk:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: petcare_api_sdk
    working_dir: /app
    volumes:
      - .:/app                     # Монтуємо всю папку PetCare
      - dotnet_tools_cache:/root/.dotnet/tools
    depends_on:
      - db
    entrypoint: ["tail", "-f", "/dev/null"]  # залишаємо контейнер активним для dotnet ef
    restart: unless-stopped

volumes:
  pgdata:
  dotnet_tools_cache:
