services:
  db:
    image: postgis/postgis:16-3.4
    container_name: petcare_db
    environment:
      POSTGRES_DB: petcare_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  petcare.api:
    build:
      context: .
      dockerfile: PetCare.Api/Dockerfile
    container_name: petcare_api
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:80"
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=petcare_db;Username=postgres;Password=postgres"

      # Email settings
      EmailSettings__SmtpServer: "smtp.gmail.com"
      EmailSettings__Port: "587"
      EmailSettings__SenderName: "PetCare"
      EmailSettings__SenderEmail: "petcare.app.noreply@gmail.com"
      EmailSettings__Username: "petcare.app.noreply@gmail.com"
      EmailSettings__Password: "zamd hyxb cmro hdgj"

       # JWT settings
      JWT_SECRET_KEY: "MyVeryLongSecretKeyForJWTTokenGeneration123456789"
      JWT_ISSUER: "PetCare.Api"
      JWT_AUDIENCE: "PetCare.Client"
      JWT_EXPIRATION_MINUTES: "15"          # короткий час для access token
      JWT_REFRESH_EXPIRATION_DAYS: "7"      # refresh token живе довше

       # SMS settings
      SmsSettings__Provider: "Twilio"
      SmsSettings__ApplicationName: "PetCare"
      SmsSettings__CodeExpirationMinutes: "5"
      SmsSettings__MaxAttemptsPerPeriod: "3"
      SmsSettings__RateLimitPeriodMinutes: "10"

      # Twilio settings
      TwilioSettings__AccountSid: "AC3736a78f2439de378c907a3ac9face06"
      TwilioSettings__AuthToken: "0e6c3b0ba254626b5aa9a0bff1e3ef97"
      TwilioSettings__FromPhoneNumber: "+14195412828"
      TwilioSettings__EnableLogging: "true"
      TwilioSettings__TimeoutSeconds: "30"

    ports:
      - '5000:80'
    volumes:
      - "${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro"
      - "${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro"
    restart: unless-stopped

  petcare.api.sdk:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: petcare_api_sdk
    working_dir: /app
    volumes:
      - .:/app                     # Монтуємо всю папку PetCare
      - dotnet_tools_cache:/root/.dotnet/tools
    depends_on:
      - db
    environment:
      DOTNET_RUNNING_IN_CONTAINER: true
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=petcare_db;Username=postgres;Password=postgres"
    entrypoint: ["tail", "-f", "/dev/null"]  # залишаємо контейнер активним для dotnet ef
    restart: unless-stopped

volumes:
  pgdata:
  dotnet_tools_cache:
